# use NGINX as base image #
FROM nginx:latest

WORKDIR /usr/share/nginx/html

#expose port 80 & 443 for incoming traffic
EXPOSE 80 443

# copy html files to default path #
COPY index.html  /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]